### ISSUE TITLE
Remove dist folder from the repo

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetforms#5]
The reasoning is the same as in https://github.com/sweetalert2/sweetalert2/issues/820

**Comment by ChronicStone** [comment]
Sorry, since I'm working full time as an intern I can only work on this on my free time.

Understood for the fist file, but I still have an issue here : I haven't been able to bundle the package as I expected with webpack.

My goal was to replace the current styling with tailwind, but for this I must configure Webpack, and setup the post as config. But as I don't have a html entry point file, and I am a newbie with webpack, I didnt figure out how to do this with my index.js file as the entry point.

@limonte if you do have an idea on how to handle this, it would help a lot

**Comment by limonte** [comment]
This task is as simple as `git rm -f dist` and commit that. The `dist` folder should not be in the repo. As a developer you will have the `dist` folder locally and when you run `npm publish`, the `dist` folder will be published to npm and available for users. But the repo should not contain built files because it creates unnecessary noise, takes unnecessary space and creates confusions when contributing.

**Comment by limonte** [comment]
> Sorry, since I'm working full time as an intern I can only work on this on my free time.

No worries, I understand that and there's no time pressure. Learn and do things with your speed. I'm here to help you.

**Comment by ChronicStone** [comment]
Done. folder cleaned, useless files removed
